<?php

	namespace Utils;

	enum Positions: int{
		case QUARTERBACK = 1;
		case HALFBACK = 2;
		case FULLBACK = 3;
		case LEFT_TACKLE = 4;
		case LEFT_GUARD = 5;
		case CENTER = 6;
		case RIGHT_GUARD = 7;
		case RIGHT_TACKLE = 8;
		case TIGHT_END = 9;
		case WIDE_RECEIVER = 10;
		case LEFT_DEFENSIVE_END = 11;
		case DEFENSIVE_TACKLE = 12;
		case RIGHT_DEFENSIVE_END = 13;
		case LEFT_OUTSIDE_LINEBACKER = 14;
		case MIDDLE_LINEBACKER = 15;
		case RIGHT_OUTSIDE_LINEBACKER = 16;
		case CORNERBACK = 17;
		case FREE_SAFETY = 18;
		case STRONG_SAFETY = 19;
		case PUNTER = 20;
		case KICKER = 21;

		const POSITION_MULTIPLIERS = [
			"QUARTERBACK" => 1,
			"HALFBACK" => 1,
			"FULLBACK" => 1,
			"LEFT_TACKLE" => 1,
			"LEFT_GUARD" => 1,
			"CENTER" => 1,
			"RIGHT_GUARD" => 1,
			"RIGHT_TACKLE" => 1,
			"TIGHT_END" => 1,
			"WIDE_RECEIVER" => 1,
			"LEFT_DEFENSIVE_END" => 1,
			"DEFENSIVE_TACKLE" => 1,
			"RIGHT_DEFENSIVE_END" => 1,
			"LEFT_OUTSIDE_LINEBACKER" => 1,
			"MIDDLE_LINEBACKER" => 1,
			"RIGHT_OUTSIDE_LINEBACKER" => 1,
			"CORNERBACK" => 1,
			"FREE_SAFETY" => 1,
			"STRONG_SAFETY" => 1,
			"PUNTER" => 1,
			"KICKER" => 1,
		];

		const QUARTERBACK_HEIGHT_RANGE = [68, 79];
		const HALFBACK_HEIGHT_RANGE = [66, 77];
		const FULLBACK_HEIGHT_RANGE = [65, 76];
		const LEFT_TACKLE_HEIGHT_RANGE = [70, 82];
		const LEFT_GUARD_HEIGHT_RANGE = [70, 82];
		const CENTER_HEIGHT_RANGE = [70, 82];
		const RIGHT_TACKLE_HEIGHT_RANGE = [70, 82];
		const RIGHT_GUARD_HEIGHT_RANGE = [70, 82];
		const TIGHT_END_HEIGHT_RANGE = [70, 80];
		const WIDE_RECEIVER_HEIGHT_RANGE = [67, 79];
		const LEFT_DEFENSIVE_END_HEIGHT_RANGE = [69, 80];
		const DEFENSIVE_TACKLE_HEIGHT_RANGE = [69, 80];
		const RIGHT_DEFENSIVE_END_HEIGHT_RANGE = [69, 80];
		const LEFT_OUTSIDE_LINEBACKER_HEIGHT_RANGE = [68, 78];
		const MIDDLE_LINEBACKER_HEIGHT_RANGE = [68, 78];
		const RIGHT_OUTSIDE_LINEBACKER_HEIGHT_RANGE = [68, 78];
		const CORNERBACK_HEIGHT_RANGE = [66, 75];
		const FREE_SAFETY_HEIGHT_RANGE = [67, 76];
		const STRONG_SAFETY_HEIGHT_RANGE = [67, 76];
		const PUNTER_HEIGHT_RANGE = [65, 77];
		const KICKER_HEIGHT_RANGE = [65, 74];

		const QUARTERBACK_WEIGHT_RANGE = [180, 265];
		const HALFBACK_WEIGHT_RANGE = [165, 240];
		const FULLBACK_WEIGHT_RANGE = [190, 270];
		const LEFT_TACKLE_WEIGHT_RANGE = [265, 400];
		const LEFT_GUARD_WEIGHT_RANGE = [265, 400];
		const CENTER_WEIGHT_RANGE = [265, 385];
		const RIGHT_TACKLE_WEIGHT_RANGE = [265, 400];
		const RIGHT_GUARD_WEIGHT_RANGE = [265, 400];
		const TIGHT_END_WEIGHT_RANGE = [200, 285];
		const WIDE_RECEIVER_WEIGHT_RANGE = [155, 220];
		const LEFT_DEFENSIVE_END_WEIGHT_RANGE = [230, 300];
		const DEFENSIVE_TACKLE_WEIGHT_RANGE = [250, 400];
		const RIGHT_DEFENSIVE_END_WEIGHT_RANGE = [230, 300];
		const LEFT_OUTSIDE_LINEBACKER_WEIGHT_RANGE = [200, 260];
		const MIDDLE_LINEBACKER_WEIGHT_RANGE = [200, 260];
		const RIGHT_OUTSIDE_LINEBACKER_WEIGHT_RANGE = [200, 260];
		const CORNERBACK_WEIGHT_RANGE = [155, 210];
		const FREE_SAFETY_WEIGHT_RANGE = [170, 225];
		const STRONG_SAFETY_WEIGHT_RANGE = [170, 225];
		const PUNTER_WEIGHT_RANGE = [150, 200];
		const KICKER_WEIGHT_RANGE = [150, 200];

		public static function getByValue(int $caseValue): ?Positions{
			foreach(self::cases() as $case){
				if ($case->value === $caseValue){
					return $case;
				}
			}

			return null;
		}
	}